version: '3.7'
services:
  web:
    image: rdany992/myblog_web
    command: gunicorn myblogg.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static_cdn
      - media_volume:/home/app/web/media_cdn
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    image: rdany992/dockerhub:myblog_django_nginx
    volumes:
      - static_volume:/home/app/web/static_cdn
      - media_volume:/home/app/web/media_cdn
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:
