# Generated by Django 3.2.3 on 2021-06-03 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
