name: docker_push_web

on:
  push:
    branches: main

jobs:
  login:
    runs-on: macos-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build app
        run: docker-compose -f "docker-compose.prod.yml"  up -d --build 
      - name: Push to hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/myblog_web:latest
